import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import type { PropsWithChildren } from "react";
import Footer from "@/components/ui/footer";
import Header from "@/components/ui/header";

import "@/styles/globals.css";

interface Props {
  params: Promise<{
    locale?: string;
  }>;
}

export const metadata: Metadata = {
  title: "Seoul Moment",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: PropsWithChildren<Props>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html className="scroll-smooth" lang={locale ?? "ko"}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main className="relative min-h-[calc(100vh-70px)]">{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
